### ISSUE TITLE
Readme change

### ISSUE THREAD

**Issue by pea1bee** [gdad-s-river/create-twitter-thread#1]
This is a pretty neat module and will be very useful for twitter bots!
 
Just one correction in the readme -

`const tweetChunks = createTwitterThreadMessages(message, '🔽');`

should read 

`const tweetChunks = createTwitterThreadMessages(longTwitterRant, '🔽');`

Cheers

**Comment by gdad-s-river** [comment]
Thanks @prashantbaid! Done.
